function [statevar_legend, output_legend] = getLegends
% Assign legends for output graphs

% State variables
statevar_legend = {'1: H_x (M)','2: K_x (M)','3: Mg_x (M)',...
    '4: Reduced NADH_x (M)',...
    '5: Reduced matrix ubiquinol (QH_2; M)',...
    '6: IMS reduced cyt-c (Cred; M)',...
    '7: O_2 (M)','8: ATP_x (M)','9: ADP_x (M)',...
    '10: Mg-bound ATP_m_x (M)','11: Mg-bound ADP_m_x (M)',...
    '12: Pi_x (M)',...
    '13: ATP_i (M)', '14: ADP_i (M)','15: AMP_i(M)',...
    '16: Mg-bound ATP_m_i (M)', '17: Mg-bound ADP_m_i (M)',...
    '18: Pi_i (M)',...
    '19: \Delta\Psi_m (mV)',...
    '20: IMS total available cyt-c (Ctot)',...
    '21: Total available Qtot',...
    '22: H_i','23: ATP_c (M)','24: ADP_c (M)'};

% Outputs
output_legend = {'1: Dehydrogenase flux (input fn; J-DH)',...
    '2: Flux through CI (J-C1)',...
    '3: Flux through CIII (J-C3)',...
    '4: Flux through CIV (J-C4; ~O2 cons)',...
    '5: Flux through ATP synthase (J-F1, ~mito. ATP prod.)',...
    '6: Flux through ANT (J-ANT)',...
    '7: ATP transfer IMS-cytosol (J-ATP)',...
    '8: ADP transfer IMS-cytosol (J-ADP)',...
    '9: H_x (Statevar1)', ...
    '10: IMS available cyt-c (Ctot; Statevar20)',...
    '11: Qtot: Total avail. ubiquinol/Complex I (Statevar21)',...
    '12: Free active Casp3',...
    '13: \Delta\Psi_m (mV; StateVar19)',...
    '14: Membrane Protomotive force (dG-H/F; mV)',...
    '15: Proton leak flux (J-Hle)',...
    '16: Cyto. ATP ratio (ATP_e/ATP_e+ADP_e)',...
    '17: \DeltapH matrix-cyto',...
    '18: Proton extrusion by C1,C2,C3 (% of total)',...
    '19: Proton generation by KH (% of total)',...
    '20: Proton cons. by input flux (% of total)',...
    '21: Proton cons. by respiration (% of total)',...
    '22. Proton cons. by P_iH (% of total)',...
    '23: Proton cons. by proton leaks (% of total)',...
    '24: Cyto. ATP_e (M; Statevar23)'...
    '25: NAD_x',...
    '26: Matrix pH'...
    '27: Cyto. ATP prod. ~ECAR'...
    '28: Cyto. ATP cons.'};

end