%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Theurey et al 2018 - Figure 1B
%%% Scatter values generated by a population
%%% and draw lines at limits of literature values
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Obtain data
checkData = 0;
if checkData == 1
%%% Data can be generated by running a population
%%% (Beard_NC_simulatePopulation.m) and obtaining the desired parameter
%%% using the below commands [need to pause simulation]
% Baseline TMRM
baselineTMRM = squeeze(stateVarAll(:,19,:)); % to get dPsim
baselineTMRM = baselineTMRM(1,:); % to get baseline value
baselineTMRM = baselineTMRM';

% Baseline cytosolic ATP
baselineATPc = squeeze(stateVarAll(:,23,:));
baselineATPc = baselineATPc(1,:); % to get baseline value
baselineATPc = baselineATPc';

% Baseline mitochondrial pH
baselinePHx = squeeze(OutputAll(:,26,:));
baselinePHx = baselinePHx(1,:); % to get baseline value
baselinePHx = baselinePHx';

else
%%% Alternatively, here is a run from 09-May-2018 (30 simulations, rng(1))
%%% (data used in Figure)
%%% See "Baseline sims.xlsx" 
baselineTMRM = [149.1696867; 149.4510064; 145.1507917; 147.2573399;...
147.6163664; 148.018499; 147.140482; 151.8918438; 145.6775149; 142.4877963;...
142.0360414; 143.4568666; 150.6289994; 152.8470695; 152.8113373; 141.5402939;...
147.0377277; 153.8923832; NaN; 149.8591836; 137.4233501; 154.084823;...
147.1113718; 154.0755925; 141.7735735; 144.3038632; 151.6752627; 140.0073662;...
149.153521; 139.5968821];

baselineATPc = [0.002317006; 0.002411988; 0.002446799; 0.00237355;...
0.002753373; 0.00219711; 0.002108882; 0.002669021; 0.002598023; 0.00236729;...
0.002472237; 0.002276503; 0.002284923; 0.001846975; 0.002306665; 0.002313164;...
0.002085244; 0.002287939; NaN; 0.002166925; 0.002516084; 0.001797033;...
0.002630918; 0.00235261; 0.002627498; 0.002412586; 0.002289641; 0.00242262;...
0.002207942; 0.00208726 ];

baselinePHx = [7.739732687; 7.727202039; 7.782567139; 7.772593699;...
7.719497835; 7.762793045; 7.785909009; 7.692044126; 7.750253268; 7.868016856;...
7.811362105; 7.836647782; 7.707577857; 7.711368384; 7.666780254; 7.83934863;...
7.801585941; 7.660475492; NaN; 7.713723941; 7.90520554; 7.684194711;...
7.706091194; 7.64912383; 7.833781411; 7.79975459; 7.693175025; 7.871799534;...
7.767404448; 7.886169897 ];

end
%%

varNameAll = {'baselineTMRM' 'baselineATPc' 'baselinePHx'};

for figureNum = 1:3

varName = varNameAll{figureNum};

if strcmp(varName, 'baselineTMRM')
    plotValue = baselineTMRM;
elseif strcmp(varName, 'baselineATPc')
    plotValue = baselineATPc;
elseif strcmp(varName, 'baselinePHx')
    plotValue = baselinePHx;
end

% Apply random x-axis scatter for plotting
plotValue(:,2) = 1;
for i = 1:size(plotValue,1)
plotValue(i,2) = plotValue(i,2) + 0.1+(0.1*rand);
end

% Change default font type to Arial
set(0,'defaultAxesFontName', 'Arial')
set(0,'defaultTextFontName', 'Arial')

% Scatter plot
% Dimensions for publication (Fig 1B)
figure('Position', [100 100 50 115])
markersize = 3;
scatter(plotValue(:,2),plotValue(:,1), markersize,'filled','k')
if strcmp(varName, 'baselineATPc')
    % Plot ATP in mM
    scatter(plotValue(:,2),plotValue(:,1)*1000, markersize,'filled','k')
end
hold on

if strcmp(varName, 'baselineTMRM')
    % Literature ranges from Gerencser 2012, Ward 2000, 
    % Nicholls & Budd 2000, Nicholls 1980, Surin 2013
    litMin = 135;
    litMax = 160;
    axesMin = 130;
    axesMax = 165;   
% Apply axes names and legend
ylabel('\Delta\Psi_m (mV)')

elseif strcmp(varName, 'baselineATPc')
    % Literature ranges from Weisova 2009, Lehninger [rinciples of biochem, 
    % Aubert 2001, 2005; DiNuzzo 2010 model, Cloutier 2009 model
    litMin = 2.2;   % in mM
    litMax = 2.7;
    axesMin = 2.0;
    axesMax = 3.0;   
ylabel('Cytosolic ATP (mM)')

elseif strcmp(varName, 'baselinePHx')
    % Literature ranges from Bolshakov 2007, Poburko 2011
    litMin = 7.5;
    litMax = 8.0;
    axesMin = 7.4;
    axesMax = 8.1;
ylabel('Mitochondrial pH')
end

% Plot think black lines at limits of literature values
plot([1.1 1.2], [litMin litMin], 'k', 'LineWidth', 1)
plot([1.1 1.2], [litMax litMax], 'k', 'LineWidth', 1)

% Apply axes limits
ylim([axesMin axesMax])
xlim([1.05 1.25])

% Apply legend
%legend('Simulations', 'Literature range')

% Remove x-axis ticks
set(gca,'XTick',[])
end
%%